[ global ]
    output_path = "../Outputs/HouseCSV/hansard"

###choose one: XML or XML_DIR
#[[ XML ]]
#    filename = "hansard/house_xmls/1975/1975_07_09.xml"


#[[ XML_DIR ]]
#    path = "hansard/house_xmls"

[[ XML_DIR ]]
    path = "hansard/house_test_xmls"

[ general_options ]
    which_house = "house"
    year = [1901,2025]
    xml_parsing = true
    edit = ["speaker_time","re","stage_direction","free_node","flatten","flatten","column_decorate","final_re"]
    csv_edit = true
    run_xml_toggle = true
    sample = true
    remove_nums = [0,1,2,3,4,5,6,7]
    xml_name_clean = false
