[ global ]
    output_path = "../Outputs/SenateCSV/hansard"

###choose one: XML or XML_DIR
[[ XML ]]
    filename = "hansard/senate_xmls/2005/2005_09_08.xml"


#[[ XML_DIR ]]
#    path = "hansard/senate_xmls"

#[[ XML_DIR ]]
#    path = "../../Download/senate_xmls"
#
#[[ XML_DIR ]]
#    path = "../../sgml2xml/senate_xmls"



[ general_options ]
    which_house = "senate"
    year = [1901,2025]
    xml_parsing = true
    edit = ["speaker_time","re","stage_direction","free_node","flatten","flatten","column_decorate","final_re"]
    csv_edit = true
    run_xml_toggle = true
    sample = true
    remove_nums = [0,1,2,3,4,5,6,7]
    xml_name_clean = false



